name: Running Tests

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client
      - name: Load test data
        run: psql -h localhost -d postgres_db -U postgres -f test/create_test_events.sql -f test/create_test_positions.sql
        env:
          PGPASSWORD: postgres
      - name: Run tests
        run: psql -h localhost -d postgres_db -U postgres -f test/test.sql
        env:
          PGPASSWORD: postgres